apiVersion: v1
kind: Service
metadata:
  name: wert-app-service
  labels:
    app: wert-app
spec:
  type: LoadBalancer
  selector:
    app: wert-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
